#!/usr/bin/env python
from random import randint


def delete(my_list, number):
    if number not in my_list:
        return print('Number not in list')
    number_index = my_list.index(number)
    del my_list[number_index]

lst = [randint(0,10) for i in range(0,10)]
iterations = 0
while len(lst)>0:
    delete(lst, randint(0,10))
    iterations += 1
    print(f'{lst}, iterations: {iterations}')

print(f'iterations : {iterations}')
