#!/usr/bin/env python
from random import randint

#Syntax: 

#list_name.remove(my_list, number) 
#Parameters:  obj: It is the object to be removed from the list.
#obj: object to be removed from the list 
#Returns:  The method does not return any value but removes the given object from the list.
#Exception: If the element doesn’t exist, it throws ValueError: list.remove(x): x not in list exception.
#Note:It removes the first occurrence of the object from the list. 
def delete(my_list, number):
    if number not in my_list:
        return print('Number not in list')
    number_index = my_list.index(number)
    del my_list[number_index]

lst = [randint(0,10) for i in range(0,10)]
''
print(lst)

iterations = 0
while len(lst)>0:
    print(f'{lst}, {iterations}')
    delete(lst, randint(0,10))
    iterations += 1

print("iterations: ", iterations)
